### ISSUE TITLE
Set up Kanban board

### ISSUE THREAD

**Issue by VicPeralta** [VicPeralta/Capstone-JavaScript#21]
# Set up Kanban board
Link to our project:
https://github.com/VicPeralta/Capstone-JavaScript/projects/1

We are a team of two members.
@VicPeralta 
@chukwuebukaVictor

**Comment by elmar8287** [comment]
Hi, 

# APPROVED  👍 🥇 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 

Congratulations! 🎉 

![](https://user-images.githubusercontent.com/64173189/128382030-38e7de91-f6f2-45cf-b54e-8068e0446e4c.gif)

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by VicPeralta** [comment]
Thanks

**Comment by elmar8287** [comment]
> Thanks

👍
